version: "3.9"
services:
  bot:
    build: .
    container_name: okbot
    volumes:
      - type: volume
        source: data
        target: "/okbot/${DATA_PATH}"
    env_file:
      - .env

volumes:
    data:
        external: false