[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    .git
  | .hg
  | .mypy_cache
  | .tox
  | venv
  | _build
  | buck-out
  | build
  | dist
  | .pytest
)/
'''

[tool.mypy]
python_version = 3.11
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
warn_unused_configs = True
warn_redundant_casts = True
warn_unreachable = True
